### ISSUE TITLE
Move interests section to content section, add missing quotes for classes

### ISSUE THREAD

**Issue by gregthompson27** [SkylerHaab/SkylerHaab.github.io#2]
https://github.com/SkylerHaab/SkylerHaab.github.io/blob/b06e89d9fd117d9fcbb8692cc48ac3a7b9eef852/index.html#L14-L16

@SkylerHaab, on lines 14 and 16 you're missing a closing `"` symbol after `nav-li` and before the `>` symbol. Those lines should look like this: `<li class="nav-li"> `.

___

https://github.com/SkylerHaab/SkylerHaab.github.io/blob/b06e89d9fd117d9fcbb8692cc48ac3a7b9eef852/index.html#L27-L39

Also, the interests section that you have on lines 31-39 should be part of content section. You should move the interests section into the `class="content"` div below the paragraph that says `Student at Northshore High` but before the closing div tag.

**Comment by JoshHunter11** [comment]
@gregthompson27 while the first issue with the closing " symbols have been fixed, the student still has to move their interests section into their content section.

**Comment by JoshHunter11** [comment]
> @gregthompson27 while the first issue with the closing " symbols have been fixed, the student still has to move their interests section into their content section.

@gregthompson27 The interests section is now in the content section, but I believe that the student needs another closing div tag before the closing main tag on line 38.
